const types = {
    SUBMIT_TODO: 'SUBMIT_TODO',
    DELETE_TODO: 'DELETE_TODO',
    UNDELETE_TODO: 'UNDELETE_TODO',
    INPUT_CHANGED: 'INPUT_CHANGED',
    REQUEST_POSTS: 'REQUEST_POSTS',
    RECEIVE_POSTS: 'RECEIVE_POSTS',
    SELECT_SUBREDDIT: 'SELECT_SUBREDDIT',
    INVALIDATE_SUBREDDIT: 'INVALIDATE_SUBREDDIT',
    SELECT_TAB: 'SELECT_TAB',
    RECEIVE_TASKS: 'RECEIVE_TASKS',
    REQUESTS_TASKS: 'REQUESTS_TASKS',
    INVALIDATE_TAB: 'INVALIDATE_TAB',
    SORT_TASKS: 'SORT_TASKS'
};

export default types;
